### ISSUE TITLE
Function 'Fade' does not take 'white' into account

### ISSUE THREAD

**Issue by StijnVdd** [ArminJo/NeoPatterns#2]
I've used the 'Fade' function to create a 'Blink' effect.

Started effect with Fade from 'black' to 'White' and in the callback 'reverse colors to to from 'White' to 'Black' again.

Part of my callBack logic:
ledStripPtr->Fade(ledStripPtr->LongValue1.Color2, ledStripPtr->Color1, 64, speedDelay);

These colors (Color1 and Color2) do not seem to include the 'White' component.

**Comment by ArminJo** [comment]
I will have a closer look at this...

**Comment by ArminJo** [comment]
Hi,
I extended the library, to process also the white part.
can you please test the version, before I release it?
Thanks
Armin

**Comment by StijnVdd** [comment]
Hi,

I've tested some of the functions and indeed I can confirm the white part is now used.

Note: I did not test every function.

Thank you very much for the quick support !

**Comment by ArminJo** [comment]
The new release ist active,
Thanks
