### ISSUE TITLE
Button presses not being registered

### ISSUE THREAD

**Issue by matiasgarcia91** [ArminJo/NeoPatterns#3]
Hello Armin!

Let me first say the library looks amazing, I've been helping my cousin set her neomatrix up and playing around with it and it has been super easy to set up with the snake game after copying all the library files.

We are having one problem though. After hooking up the buttons and setting the right pins we can't get the 2 button mode to work. If we start the Arduino it seems like the button presses are not being picked up. After Serial.printing the state of the button I can see the inputs are being registered in code, but I can't find where the library handles the button pressess. I can see the `sButtonWasPressed` variable but can't see where/if this var is updated with the button pressed anywhere. If you have some time and can clear this up for us it would be great.

Thanks again!
Matias

**Comment by ArminJo** [comment]
Tomorrow :-)

**Comment by ArminJo** [comment]
Hello Matias,
thanks for testing 👍 , I found the bug.
Maybe you can download the repo content, check it again and give me some feedback?
If your feedback is OK, I will then release a fixed version.

**Comment by S4M3R** [comment]
Hi, Armin, hope everything it ok!

Im still having problems with the buttons on the snake game. It recognize that we press a button, but it has a delay and some times it not detecting it. Im now helping Matias cousin. 

Thanks again!
Cheers!

**Comment by ArminJo** [comment]
Thanks for the video. 
For the mechanical buttons you only need 2 wires, button and ground!
And I rechecked the software, it looks like you have mechanical / electrical problems with your buttons.
You can enable the line `Serial.println(F("Button released")); `in MatrixSnake.cpp to have debug output.

**Comment by ArminJo** [comment]
Or you get the latest version from the repo and try the serial control, just to be sure 😀
