### ISSUE TITLE
Conflict with USB Host Shield Library

### ISSUE THREAD

**Issue by Eebel** [ArminJo/NeoPatterns#4]
Hi,

The NeoPixel.h library conflicts with the USB_Host_Shield_2.0 library. When I attempt to compile the project, I get a series of errors with the colors, White, Red, Green, and Blue. Here is an example:

In file included from C:\Users\timhe\Documents\Arduino\libraries\NeoPatterns\src/NeoPatterns.h:45:0,
from C:\Users\timhe\Documents\Arduino\Chopper-SHADOW\Chopper-SHADOW.ino:97:
C:\Users\timhe\Documents\Arduino\libraries\NeoPatterns\src/NeoPixel.h:60:28: error: 'uint8_t Red(color32_t)' redeclared as different kind of symbol
uint8_t Red(color32_t color);
^
In file included from C:\Users\timhe\Documents\Arduino\libraries\USB_Host_Shield_Library_2.0/PS3Enums.h:21:0,
from C:\Users\timhe\Documents\Arduino\libraries\USB_Host_Shield_Library_2.0/PS3BT.h:22,
from C:\Users\timhe\Documents\Arduino\Chopper-SHADOW\Chopper-SHADOW.ino:88:
C:\Users\timhe\Documents\Arduino\libraries\USB_Host_Shield_Library_2.0/controllerEnums.h:47:9: note: previous declaration 'ColorsEnum Red'
Red = 0xFF0000,
^~~

I was wondering if there was a way to resolve the issue. I am not a super strong programmer, so I don't know the correct term. But maybe the colors could be made an internal or private variable?  My workaround for the last two years has been to modify the name in the NeoPixel.h code so the conflict goes away. The problem is when I update to the library I have to rehack the code.

Or is there another more elegant way for resolving this without changing the code in the library?

Thanks,

Tim

**Comment by ArminJo** [comment]
I renamed the functions. They are not longer used internally
All you have to do for the next release is to remove the old definitions kept for backwards compatibility for the next few releases.

**Comment by Eebel** [comment]
Awesome,  thanks,

Tim

Sent from my iPhone 11 Pro Max
Aren't you impressed?

On Mar 2, 2021, at 05:56, Armin <notifications@github.com> wrote:

﻿

I renamed the functions. They are not longer used internally
All you have to do for the next release is to remove the old definitions kept for backwards compatibility for the next few releases.
