### ISSUE TITLE
5 rings one sketch

### ISSUE THREAD

**Issue by Eebel** [ArminJo/NeoPatterns#5]
Hi, I have five NeoPixel rings with 8 LEDs on each ring.  I am going to wire the rings together so they all run off of one pin as the plane where they will be installed is tight and it would be tough to send wires to a pin on the Arduino for each ring.  I've tried to setup a test of this using the AllPatternsOnMultipleDevices example as a basis for my project.  It's a short sketch.  However, I get a 
"variable or field 'PatternHandler' declared void" error when I try to compile.  What am I doing wrong?

`#include <Arduino.h>

// Which pin on the Arduino is connected to the NeoPixels?

void PatternHandler(NeoPatterns *aLedsPtr);

#define PIN_NEOPIXEL_ALL        6

NeoPatterns allPixel = NeoPatterns(40, PIN_NEOPIXEL_ALL, NEO_GRB + NEO_KHZ800, &PatternHandler);
NeoPatterns ring1 = NeoPatterns(&allPixel, 0, 8, true, &PatternHandler);
NeoPatterns ring2 = NeoPatterns(&allPixel, 9, 8, true, &PatternHandler);
NeoPatterns ring3 = NeoPatterns(&allPixel, 18, 8, true, &PatternHandler);
NeoPatterns ring4 = NeoPatterns(&allPixel, 28, 8, true, &PatternHandler);
NeoPatterns ring5 = NeoPatterns(&allPixel, 37, 8, true, &PatternHandler);

void setup() {
  Serial.begin(115200);

  ring1.begin();
  ring2.begin();
  ring3.begin();
  ring4.begin();
  ring5.begin();

  ring1.PixelFlags |= PIXEL_FLAG_GEOMETRY_CIRCLE;
  ring2.PixelFlags |= PIXEL_FLAG_GEOMETRY_CIRCLE;
  ring3.PixelFlags |= PIXEL_FLAG_GEOMETRY_CIRCLE;
  ring4.PixelFlags |= PIXEL_FLAG_GEOMETRY_CIRCLE;
  ring5.PixelFlags |= PIXEL_FLAG_GEOMETRY_CIRCLE;

  delay(300); // to avoid partial patterns at power up

  ring1.ColorWipe(COLOR32_PURPLE, 50);
  ring2.ColorWipe(COLOR32_RED, 50);
  ring3.ColorWipe(COLOR32_GREEN, 50);
  ring4.ColorWipe(COLOR32_BLUE, 50);
  ring5.ColorWipe(COLOR32_ORANGE, 50);

//    bar24.ScannerExtended(COLOR32_BLUE, 5, 50, 1,
//            FLAG_SCANNER_EXT_ROCKET | FLAG_SCANNER_EXT_VANISH_COMPLETE | FLAG_SCANNER_EXT_START_AT_BOTH_ENDS);

  Serial.println("started");
}

void loop() {
  ring1.update();
  ring2.update();
  ring3.update();
  ring4.update();
  ring5.update();

}

void PatternHandler(NeoPatterns *aLedsPtr) {
      static int8_t sState = 0;

    switch (sState) {
    case 0:
        aLedsPtr->ColorWipe(COLOR32_RED_HALF, 50);
        break;
    case 1:
        aLedsPtr->Delay(500);
        break;
    case 2:
        aLedsPtr->Heartbeat(COLOR32_GREEN, 50, 0);
        break;
    case 3:
        aLedsPtr->Delay(500);
        break;
    case 4:
        aLedsPtr->RainbowCycle(50, DIRECTION_UP);
        break;
    case 5:
        aLedsPtr->RainbowCycle(50, DIRECTION_DOWN);
        break;
    case 6:
        aLedsPtr->Delay(400);
        break;
    case 7:
        aLedsPtr->Fire(20, 400); // OK Fire(30, 260)is also OK
        break;
    case 8:
        // switch to random
        initMultipleFallingStars(aLedsPtr, COLOR32_WHITE_HALF, 7, 30, 3, &allPatternsRandomHandler);
        sState = -1; // Start from beginning
        break;
    default:
        Serial.println("ERROR");
        break;
    }

    Serial.print("PatterHandler: Pin=");
    Serial.print(aLedsPtr->getPin());
    Serial.print(" Length=");
    Serial.print(aLedsPtr->numPixels());
    Serial.print(" ActivePattern=");
    aLedsPtr->printPatternName(aLedsPtr->ActivePattern, &Serial);
    Serial.print("|");
    Serial.print(aLedsPtr->ActivePattern);
    Serial.print(" State=");
    Serial.println(sState);

    sState++;
}
`

**Comment by ArminJo** [comment]
Try #include "NeoPatterns.h"

**Comment by Eebel** [comment]
Thanks. I noticed that include was not in the example.

Thanks, it compiles now.

Tim

Sent from my iPhone 11 Pro Max
Aren't you impressed?

On Nov 21, 2021, at 16:45, Armin ***@***.***> wrote:

﻿

Try #include "NeoPatterns.h"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FArminJo%2FNeoPatterns%2Fissues%2F5%23issuecomment-974911364&data=04%7C01%7C%7Ca197ba2c8d6849dda7ae08d9ad4092d3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637731315116330633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3MxuHhfBIj7Z2iofRV9OUv0o6V227OJLdTB6%2BruQYkI%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAIWW7DPKBSAJY7OUFTHUI3UNFY7LANCNFSM5IPTMCHA&data=04%7C01%7C%7Ca197ba2c8d6849dda7ae08d9ad4092d3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637731315116330633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Clv8yZhReAoAIGQZLboDXPvh%2B5PA5kYVS9pYMHp%2F1ms%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca197ba2c8d6849dda7ae08d9ad4092d3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637731315116340588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YEDINn%2FeOQ9wHP8aBXBwTJe1Vj9Iwq6UVXB0oGTO%2F7A%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca197ba2c8d6849dda7ae08d9ad4092d3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637731315116340588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TYq5lNSgmTiuMtKdy%2BMeK6VLT69eRmxdauHRygiC5tQ%3D&reserved=0>.
