### ISSUE TITLE
glitch when Fade() active on more than one pin/NeoPixel

### ISSUE THREAD

**Issue by drepetto** [ArminJo/NeoPatterns#8]
Thank you for writing this library, it is very useful.

I am using five NeoPixels, each on a different pin. If I have more than one Fade() running at a time there will be a glitch where the color from one NoePixel will suddenly appear on a different NeoPixel for a moment at the beginning of a new Fade(). This seems like it might be a memory management issue? Maybe there is a shared resource somewhere that is accidentally being referenced?

**Comment by drepetto** [comment]
For a little more context, I am working on a simple sketch right now where the five NeoPixels are just constantly doing Fade() to a new color, each independently in terms of speed and color. Thanks.

**Comment by ArminJo** [comment]
Thanks for reporting!
The closing brace for` if (aDoUpdate) {` was after the refresh section. It must be before the refresh section.
```
    if (aDoUpdate) {
        if (decrementTotalStepCounterAndSetNextIndex()) {
            return true;
        }
    } // This was placed wrong before
```

**Comment by drepetto** [comment]
Thanks!  Fade() works perfectly for me now.

It looks like the same bug might appear in several update() methods...

**Comment by ArminJo** [comment]
I checked all the others... and found it only in fade.

**Comment by drepetto** [comment]
Ah, I see now. There was more to be done in some of the other patterns. Thanks again!
